# Generated by Django 5.2.3 on 2025-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_rename_name_blogger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='image',
            field=models.FileField(default=1, upload_to='blogger_image/'),
            preserve_default=False,
        ),
    ]
